server:
  port: 8080
spring:
  rsocket:
    server:
      mapping-path: /rs
      transport: websocket
      port: 7000
  data:
    mongodb:
      uri: mongodb://0.0.0.0:27017/chat_server
  rabbitmq:
    port: 15672
    host: localhost
    username: test
    password: test